### What is NumPy Used For?
`NumPy` is `designed` to: 
- ✅ `Perform fast mathematical` operations on `large data arrays`.
- ✅ Efficiently handle multi-dimensional arrays (also called ndarrays).
- ✅ Provide a rich collection of mathematical functions for operations like algebra, statistics, and Fourier transformations.
- ✅ Enable powerful tools for array slicing, indexing, and reshaping data.
- ✅ Act as a foundation for other libraries like Pandas, Scikit-learn, and TensorFlow.

In [1]:
!pip install numpy

#### 3.1 Creating Arrays in NumPy
- NumPy's core data structure is the ndarray (N-dimensional array).
- Example: Creating 1D and 2D Arrays

In [7]:
import numpy as np

# 1D Array
arr1 = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1)

# 2D Array (Matrix)
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)


1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


#### 3.2 Array Shape, Size, and Data Type
- `.shape` → Returns the array’s dimensions.
- `.size` → Returns the total number of elements.
- `.dtype` → Returns the data type of elements.
- Example:

In [8]:
print("Shape:", arr2.shape)    # (2, 3) → 2 rows, 3 columns
print("Size:", arr2.size)      # 6 → Total elements
print("Data Type:", arr2.dtype)  # int64


Shape: (2, 3)
Size: 6
Data Type: int64


#### 3.3 Creating Special Arrays
- NumPy has functions to create special arrays efficiently:

- `np.zeros()`	Creates an array filled with zeros.
- `np.ones()`	Creates an array filled with ones.
- `np.arange()`	Creates an array with a range of values.
- `np.linspace()`	Creates an array with evenly spaced values.
- Example:

In [9]:
print(np.zeros((2, 3)))         # 2x3 array filled with zeros
print(np.ones((3, 2)))          # 3x2 array filled with ones
print(np.arange(1, 10, 2))      # [1 3 5 7 9] → Range from 1 to 9 with step 2
print(np.linspace(1, 5, 4))     # [1. 2.333 3.667 5.] → 4 evenly spaced values


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[1 3 5 7 9]
[1.         2.33333333 3.66666667 5.        ]


#### 3.4 Basic Mathematical Operations
- NumPy supports element-wise arithmetic.


In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)         # [5 7 9]
print("Subtraction:", a - b)      # [-3 -3 -3]
print("Multiplication:", a * b)   # [4 10 18]
print("Division:", a / b)         # [0.25 0.4 0.5]
print("Power:", a ** 2)           # [1 4 9]


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]


#### 3.5 Array Indexing and Slicing
- NumPy allows powerful slicing and indexing techniques.


In [11]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[1])      # 20 → Access element at index 1
print(arr[1:4])    # [20 30 40] → Slice from index 1 to 3
print(arr[::-1])   # [50 40 30 20 10] → Reverse the array


20
[20 30 40]
[50 40 30 20 10]


#### 3.6 Reshaping Arrays
- Reshape data into different dimensions.


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)  # Reshape into 2 rows and 3 columns
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


#### 3.7 Aggregation Functions
- NumPy provides built-in functions for aggregation like sum(), mean(), min(), max().

In [13]:
data = np.array([1, 2, 3, 4, 5])

print("Sum:", np.sum(data))           # 15
print("Mean:", np.mean(data))         # 3.0
print("Min:", np.min(data))           # 1
print("Max:", np.max(data))           # 5
print("Standard Deviation:", np.std(data))  # 1.414


Sum: 15
Mean: 3.0
Min: 1
Max: 5
Standard Deviation: 1.4142135623730951


#### 3.8 Matrix Operations
- NumPy simplifies linear algebra calculations.


In [14]:
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])

# Matrix Multiplication
result = np.dot(A, B)
print("Matrix Multiplication:\n", result)


Matrix Multiplication:
 [[19 22]
 [43 50]]


#### 3.9 Random Number Generation
- NumPy provides functions for generating random numbers.

In [15]:
random_data = np.random.rand(3, 3)  # 3x3 array of random values between 0 and 1
print(random_data)


[[0.15859322 0.15083554 0.89567895]
 [0.57655025 0.45063749 0.8698032 ]
 [0.33548008 0.82301194 0.63408923]]


#### 3.10 Filtering with Conditions
- NumPy makes it easy to filter data based on conditions.


In [16]:
arr = np.array([10, 25, 30, 45, 60])
filtered_data = arr[arr > 30]  # Filter values greater than 30
print("Filtered Data:", filtered_data)


Filtered Data: [45 60]


### 4. Key Takeaways
- ✅ NumPy is essential for data manipulation, numerical operations, and efficient handling of large datasets.
- ✅ It provides powerful tools for array creation, mathematical functions, matrix operations, and random number generation.
- ✅ NumPy’s efficient array handling makes it faster and more memory-efficient than standard Python lists for large-scale data.